/*Queries that provide answers to the questions from all projects.*/

SELECT * from animals WHERE name = 'Luna';
SELECT * FROM animals WHERE name LIKE '%mon';
SELECT * FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
SELECT * FROM animals WHERE neutered=true AND escape_attempts < 3;
SELECT date_of_birth FROM animals WHERE name='Agumon' OR name='Pikachu';
SELECT name, escape_attempts FROM animals WHERE weight_kg > 10.5;
SELECT * FROM animals WHERE neutered=true;
SELECT * FROM animals WHERE name NOT IN ('Gabumon');
SELECT * FROM animals WHERE (weight_kg >= 10.4 AND weight_kg <= 17.3);
BEGIN;
UPDATE animals SET species = 'unspecified';
ROLLBACK;
SELECT * FROM animals;
BEGIN;
UPDATE animals SET species = 'digimon' WHERE Name like '%mon';
UPDATE animals SET species = 'pokemon' WHERE species IS NULL;
COMMIT;
SELECT * FROM animals;
BEGIN;
DELETE FROM animals;
ROLLBACK;
SELECT * FROM animals;
BEGIN;
DELETE FROM animals WHERE date_of_birth > '2022-01-01';
SAVEPOINT my_savepoint;
UPDATE animals SET weight_kg = weight_kg * -1;
ROLLBACK TO SAVEPOINT my_savepoint;
UPDATE animals SET weight_kg = weight_kg * -1 WHERE weight_kg < 0;
COMMIT;
SELECT count(*) FROM animals;
SELECT count(*) FROM animals WHERE escape_attempts = 0;
SELECT avg(weight_kg) FROM animals;
SELECT neutered, max(escape_attempts) AS max_escape_attempts FROM animals GROUP BY neutered;
SELECT species, avg(escape_attempts) AS avg_escape_attempts FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31' GROUP BY species;
SELECT species, min(weight_kg) AS min_weight, max(weight_kg) AS max_weight FROM animals GROUP BY species;

SELECT * FROM animals JOIN owners ON animals.owner_id = owners.id WHERE full_name='Melody Pond';
SELECT animals.name, species.name FROM animals JOIN species ON animals.species_id=species.id WHERE species.name = 'Pokemon';
SELECT owners.full_name, animals.name AS animal_name FROM owners LEFT JOIN animals ON owners.id=animals.owner_id;
SELECT s.name, COUNT(*) AS animal_count FROM species s LEFT JOIN animals a ON s.id = a.species_id GROUP BY s.name;
SELECT a.name FROM animals a JOIN species s ON a.species_id = s.id JOIN owners o ON a.owner_id = o.id WHERE s.name = 'Digimon' AND o.full_name = 'Jennifer Orwell';
SELECT animals.name FROM animals JOIN owners ON animals.owner_id=owners.id WHERE owners.full_name = 'Dean Winchester' AND animals.escape_attempts<1;
SELECT owners.full_name, COUNT(animals.name) AS all_animals from animals JOIN owners ON animals.owner_id = owners.id GROUP BY owners.full_name ORDER BY all_animals DESC LIMIT 1;

SELECT a.name FROM animals a JOIN visits vs ON a.id = vs.animal_id JOIN vets vet ON vet.id = vs.vet_id WHERE vet.name = 'Vet William Tatcher' ORDER BY vs.visit_date DESC LIMIT 1;
SELECT COUNT(DISTINCT vs.animal_id) AS animals_number FROM visits vs JOIN vets vet ON vet.id = vs.vet_id WHERE vet.name = 'Vet Stephanie Mendez';
SELECT vt.name, s.name AS specialization FROM vets vt LEFT JOIN specializations sp ON vt.id = sp.vet_id LEFT JOIN species s ON s.id = sp.species_id;
SELECT an.name FROM animals an JOIN visits vs ON an.id = vs.animal_id JOIN vets vet ON vet.id = vs.vet_id WHERE vet.name = 'Vet Stephanie Mendez' AND vs.visit_date BETWEEN '2020-04-01' AND '2020-08-30';
SELECT an.name, COUNT(*) AS visit_number FROM animals an JOIN visits vs ON an.id = vs.animal_id GROUP BY an.name ORDER BY visit_number DESC LIMIT 1;
SELECT animals.name AS animal_name, vets.name AS vet_name, visits.visit_date FROM visits JOIN vets ON visits.vet_id = vets.id JOIN animals ON visits.animal_id = animals.id WHERE vets.name = 'Vet Maisy Smith' ORDER BY visit_date LIMIT 1;
SELECT a.name AS animal_name, vet.name AS vet_name, vs.visit_date FROM animals a JOIN visits vs ON a.id = vs.animal_id JOIN vets vet ON vet.id = vs.vet_id ORDER BY vs.visit_date DESC LIMIT 1; 
SELECT COUNT(*) AS mismatched_visits FROM visits vs JOIN vets vet ON vet.id = vs.vet_id JOIN animals a ON a.id = vs.animal_id LEFT JOIN specializations sp ON sp.vet_id = vet.id AND sp.species_id = a.species_id WHERE sp.vet_id IS NULL;
SELECT s.name AS potential_specialty FROM animals a JOIN visits v ON a.id = v.animal_id JOIN vets vt ON vt.id = v.vet_id JOIN owners o ON o.id = a.owner_id JOIN species s ON s.id = a.species_id WHERE vt.name = 'Vet Maisy Smith' GROUP BY s.name ORDER BY COUNT(*) DESC LIMIT 1;
